import { Ingredient, Meal } from './types';

export const INVENTED_INGREDIENTS: Ingredient[] = [
  // Proteins
  { id: 'ing_chicken', name: 'Chicken Breast', category: 'Proteins', emoji: '🍗', commonUnit: 'g', suggestedPantry: true },
  { id: 'ing_eggs', name: 'Eggs', category: 'Proteins', emoji: '🥚', commonUnit: 'pcs', suggestedPantry: true },
  { id: 'ing_tofu', name: 'Firm Tofu', category: 'Proteins', emoji: '🧊', commonUnit: 'g', suggestedPantry: false },
  { id: 'ing_tuna', name: 'Canned Tuna', category: 'Proteins', emoji: '🐟', commonUnit: 'can', suggestedPantry: true },
  { id: 'ing_beef', name: 'Minced Beef', category: 'Proteins', emoji: '🥩', commonUnit: 'g', suggestedPantry: false },
  { id: 'ing_shrimp', name: 'Fresh Shrimp', category: 'Proteins', emoji: '🦐', commonUnit: 'g', suggestedPantry: false },

  // Vegetables
  { id: 'ing_garlic', name: 'Garlic', category: 'Vegetables', emoji: '🧄', commonUnit: 'cloves', suggestedPantry: true },
  { id: 'ing_onion', name: 'Yellow Onion', category: 'Vegetables', emoji: '🧅', commonUnit: 'pcs', suggestedPantry: true },
  { id: 'ing_tomato', name: 'Fresh Tomatoes', category: 'Vegetables', emoji: '🍅', commonUnit: 'pcs', suggestedPantry: true },
  { id: 'ing_broccoli', name: 'Broccoli', category: 'Vegetables', emoji: '🥦', commonUnit: 'heads', suggestedPantry: true },
  { id: 'ing_spinach', name: 'Fresh Spinach', category: 'Vegetables', emoji: '🥬', commonUnit: 'g', suggestedPantry: false },
  { id: 'ing_bell_pepper', name: 'Bell Pepper', category: 'Vegetables', emoji: '🫑', commonUnit: 'pcs', suggestedPantry: false },
  { id: 'ing_carrot', name: 'Carrots', category: 'Vegetables', emoji: '🥕', commonUnit: 'pcs', suggestedPantry: true },
  { id: 'ing_mushroom', name: 'Cremini Mushrooms', category: 'Vegetables', emoji: '🍄', commonUnit: 'g', suggestedPantry: false },

  // Grains & Carbs
  { id: 'ing_rice', name: 'Jasmine Rice', category: 'Grains & Carbs', emoji: '🍚', commonUnit: 'cups', suggestedPantry: true },
  { id: 'ing_pasta', name: 'Pasta (Spaghetti/Penne)', category: 'Grains & Carbs', emoji: '🍝', commonUnit: 'g', suggestedPantry: true },
  { id: 'ing_potatoes', name: 'Russet Potatoes', category: 'Grains & Carbs', emoji: '🥔', commonUnit: 'pcs', suggestedPantry: true },
  { id: 'ing_oats', name: 'Rolled Oats', category: 'Grains & Carbs', emoji: '🥣', commonUnit: 'cups', suggestedPantry: false },
  { id: 'ing_bread', name: 'Sliced Bread', category: 'Grains & Carbs', emoji: '🍞', commonUnit: 'slices', suggestedPantry: false },

  // Dairy & Eggs
  { id: 'ing_cheese', name: 'Cheddar Cheese', category: 'Dairy & Eggs', emoji: '🧀', commonUnit: 'g', suggestedPantry: false },
  { id: 'ing_milk', name: 'Fresh Milk', category: 'Dairy & Eggs', emoji: '🥛', commonUnit: 'ml', suggestedPantry: false },
  { id: 'ing_butter', name: 'Unsalted Butter', category: 'Dairy & Eggs', emoji: '🧈', commonUnit: 'tbsp', suggestedPantry: true },

  // Pantry & Seasonings
  { id: 'ing_olive_oil', name: 'Olive Oil', category: 'Pantry & Seasonings', emoji: '🫒', commonUnit: 'tbsp', suggestedPantry: true },
  { id: 'ing_soy_sauce', name: 'Soy Sauce', category: 'Pantry & Seasonings', emoji: '🥢', commonUnit: 'tbsp', suggestedPantry: true },
  { id: 'ing_black_pepper', name: 'Black Pepper', category: 'Pantry & Seasonings', emoji: '🧂', commonUnit: 'pinch', suggestedPantry: true },
  { id: 'ing_salt', name: 'Table Salt', category: 'Pantry & Seasonings', emoji: '🧂', commonUnit: 'pinch', suggestedPantry: true },
];

export const INVENTED_MEALS: Meal[] = [
  {
    id: 'meal_egg_fried_rice',
    name: 'Golden Garlic Egg Fried Rice',
    shortDescription: 'Fragrant day-old rice tossed with scrambled eggs, caramelized garlic, and savory soy seasoning.',
    category: 'Quick & Easy',
    difficulty: 'Easy',
    baseServings: 2,
    prepTimeMinutes: 5,
    cookingTimeMinutes: 10,
    totalTimeMinutes: 15,
    caloriesPerServing: 410,
    protein: 15,
    carbohydrates: 58,
    fat: 13,
    fitnessSuitability: false,
    emoji: '🍳',
    chefTip: 'Use chilled or day-old cooked rice so grains separate cleanly in the hot pan.',
    tags: ['Comfort', 'Budget Friendly', '15 Min'],
    ingredients: [
      { ingredientId: 'ing_rice', name: 'Jasmine Rice (cooked)', amount: 2, unit: 'cups' },
      { ingredientId: 'ing_eggs', name: 'Eggs', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 3, unit: 'cloves' },
      { ingredientId: 'ing_onion', name: 'Yellow Onion', amount: 0.5, unit: 'pcs' },
      { ingredientId: 'ing_soy_sauce', name: 'Soy Sauce', amount: 1.5, unit: 'tbsp' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 1.5, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Finely mince garlic and dice the half yellow onion.',
      'Beat the eggs lightly in a bowl with a small pinch of salt.',
      'Heat 1 tbsp olive oil in a wide skillet or wok over medium-high heat. Pour in beaten eggs and scramble softly for 60 seconds. Transfer eggs to a plate.',
      'Add remaining oil to the pan, then sauté garlic and onion until golden and aromatic (about 2 minutes).',
      'Add the cooked rice, breaking up any clumps with a spatula. Drizzle soy sauce around the pan edges and stir vigorously for 3 minutes.',
      'Fold the scrambled eggs back into the rice, season with freshly cracked black pepper, and serve hot.',
    ],
  },
  {
    id: 'meal_lemon_herb_chicken',
    name: 'Seared Garlic Herb Chicken & Broccoli',
    shortDescription: 'Tender chicken cutlets seared with garlic crisps and tender-crisp steamed broccoli florets.',
    category: 'Fitness',
    difficulty: 'Easy',
    baseServings: 2,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 15,
    totalTimeMinutes: 25,
    caloriesPerServing: 330,
    protein: 43,
    carbohydrates: 11,
    fat: 12,
    fitnessSuitability: true,
    emoji: '🥗',
    chefTip: 'Pat the chicken breasts dry with a paper towel before searing to achieve a golden crust.',
    tags: ['High Protein', 'Low Carb', 'Post-Workout'],
    ingredients: [
      { ingredientId: 'ing_chicken', name: 'Chicken Breast', amount: 400, unit: 'g' },
      { ingredientId: 'ing_broccoli', name: 'Broccoli', amount: 1, unit: 'heads' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 4, unit: 'cloves' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 1.5, unit: 'tbsp' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Slice chicken breasts horizontally into even cutlets. Season both sides with salt and black pepper.',
      'Cut broccoli into bite-sized florets and thinly slice garlic cloves.',
      'Heat 1 tbsp olive oil in a non-stick skillet over medium-high heat. Sear chicken for 4-5 minutes per side until thoroughly cooked (internal temp 74°C / 165°F). Set aside to rest.',
      'In the same skillet, add the remaining oil and sliced garlic. Sauté for 30 seconds until fragrant.',
      'Add broccoli florets with 2 tbsp of water. Cover with a lid to steam for 3 minutes until bright green and tender.',
      'Slice chicken and arrange over warm broccoli. Drizzle any pan juices on top and serve.',
    ],
  },
  {
    id: 'meal_creamy_tomato_pasta',
    name: 'Creamy One-Pan Tomato Spinach Pasta',
    shortDescription: 'Silky pasta tossed in a fresh tomato and melted cheese sauce with wilted tender spinach.',
    category: 'Family Meal',
    difficulty: 'Easy',
    baseServings: 4,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 20,
    totalTimeMinutes: 30,
    caloriesPerServing: 475,
    protein: 18,
    carbohydrates: 69,
    fat: 15,
    fitnessSuitability: false,
    emoji: '🍝',
    chefTip: 'Save half a cup of starchy pasta cooking water to make the cheese emulsion extra creamy.',
    tags: ['Kid Friendly', 'One Pan', 'Crowd Pleaser'],
    ingredients: [
      { ingredientId: 'ing_pasta', name: 'Pasta (Spaghetti/Penne)', amount: 350, unit: 'g' },
      { ingredientId: 'ing_tomato', name: 'Fresh Tomatoes', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_spinach', name: 'Fresh Spinach', amount: 150, unit: 'g' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 3, unit: 'cloves' },
      { ingredientId: 'ing_onion', name: 'Yellow Onion', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_cheese', name: 'Cheddar Cheese', amount: 100, unit: 'g' },
      { ingredientId: 'ing_milk', name: 'Fresh Milk', amount: 120, unit: 'ml' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 2, unit: 'tbsp' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Bring a large pot of salted water to boil. Cook pasta al dente according to box instructions (about 9 minutes). Drain and reserve 1/2 cup pasta water.',
      'Dice tomatoes and finely chop onion and garlic.',
      'In a wide skillet, heat olive oil over medium heat. Cook onion and garlic until translucent and fragrant (3 minutes).',
      'Add chopped tomatoes and simmer for 6 minutes until soft and saucy, gently crushing with a spoon.',
      'Pour in milk and simmer gently for 2 minutes. Stir in grated cheddar cheese until melted and smooth.',
      'Toss in cooked pasta and fresh spinach. Stir for 1 minute until spinach wilts and sauce coats pasta. Season to taste.',
    ],
  },
  {
    id: 'meal_tofu_veggie_stirfry',
    name: 'Crispy Golden Tofu & Garden Stir-Fry',
    shortDescription: 'Pan-seared tofu cubes glazed in soy garlic sauce with crisp bell peppers, broccoli, and mushrooms.',
    category: 'Fitness',
    difficulty: 'Medium',
    baseServings: 2,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 20,
    totalTimeMinutes: 30,
    caloriesPerServing: 315,
    protein: 24,
    carbohydrates: 20,
    fat: 16,
    fitnessSuitability: true,
    emoji: '🥢',
    chefTip: 'Press the tofu with a clean kitchen towel for 5 minutes before cubing to get maximum crispiness.',
    tags: ['Plant Power', 'High Fiber', 'Balanced Macros'],
    ingredients: [
      { ingredientId: 'ing_tofu', name: 'Firm Tofu', amount: 300, unit: 'g' },
      { ingredientId: 'ing_bell_pepper', name: 'Bell Pepper', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_broccoli', name: 'Broccoli', amount: 0.5, unit: 'heads' },
      { ingredientId: 'ing_mushroom', name: 'Cremini Mushrooms', amount: 120, unit: 'g' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 2, unit: 'cloves' },
      { ingredientId: 'ing_soy_sauce', name: 'Soy Sauce', amount: 2, unit: 'tbsp' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 1.5, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Cut tofu into 2cm bite-sized cubes. Pat thoroughly dry with paper towels.',
      'Chop bell pepper into strips, cut broccoli into small florets, and slice mushrooms.',
      'Heat 1 tbsp olive oil in a wide pan over medium-high heat. Pan-fry tofu undisturbed for 3-4 minutes per side until golden brown all around. Transfer to a plate.',
      'Add remaining oil to pan. Stir-fry garlic, mushrooms, broccoli, and bell pepper over high heat for 4 minutes until tender-crisp.',
      'Return crispy tofu to the skillet. Pour soy sauce and a splash of water over the vegetables and tofu, tossing quickly for 1 minute.',
      'Finish with fresh black pepper and serve immediately.',
    ],
  },
  {
    id: 'meal_rustic_beef_potato',
    name: 'Hearty Rustic Beef & Potato Skillet',
    shortDescription: 'Savory minced beef browned with golden skillet-fried potatoes, sweet onions, and melted butter.',
    category: 'Family Meal',
    difficulty: 'Medium',
    baseServings: 4,
    prepTimeMinutes: 15,
    cookingTimeMinutes: 35,
    totalTimeMinutes: 50,
    caloriesPerServing: 520,
    protein: 33,
    carbohydrates: 44,
    fat: 24,
    fitnessSuitability: false,
    emoji: '🥘',
    chefTip: 'Parboil or microwave diced potatoes for 3 minutes first to slash skillet frying time in half.',
    tags: ['Cozy Dinner', 'High Energy', 'Hearty'],
    ingredients: [
      { ingredientId: 'ing_beef', name: 'Minced Beef', amount: 450, unit: 'g' },
      { ingredientId: 'ing_potatoes', name: 'Russet Potatoes', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_onion', name: 'Yellow Onion', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 3, unit: 'cloves' },
      { ingredientId: 'ing_bell_pepper', name: 'Bell Pepper', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_butter', name: 'Unsalted Butter', amount: 2, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Peel and cut potatoes into 1.5cm dice. Finely chop the onion, mince garlic, and dice bell pepper.',
      'In a large skillet over medium-high heat, melt 1 tbsp butter. Add diced potatoes with salt and cook undisturbed for 5 minutes, then stir and cook until browned and fork-tender (about 12 minutes). Remove to a bowl.',
      'In the same skillet, add minced beef, chopped onion, and garlic. Cook, breaking meat into small crumbles, until browned and cooked through (about 7 minutes). Drain excess rendered grease if needed.',
      'Add diced bell pepper and cook for 3 minutes until softened.',
      'Return crispy potatoes to the skillet, add the remaining 1 tbsp butter, and toss everything together for 2 minutes.',
      'Season generously with black pepper and salt. Serve warm straight from the pan.',
    ],
  },
  {
    id: 'meal_mediterranean_tuna_salad',
    name: 'Zesty Mediterranean Tuna & Egg Bowl',
    shortDescription: 'Flaked tuna, soft-boiled eggs, crisp spinach, juicy tomatoes, and peppers drizzled with olive oil.',
    category: 'Quick & Easy',
    difficulty: 'Easy',
    baseServings: 1,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 5,
    totalTimeMinutes: 15,
    caloriesPerServing: 325,
    protein: 38,
    carbohydrates: 9,
    fat: 15,
    fitnessSuitability: true,
    emoji: '🥗',
    chefTip: 'Drain tuna thoroughly before mixing so the delicate salad greens remain crisp and fresh.',
    tags: ['No Cooking Required', 'High Protein', '15 Min'],
    ingredients: [
      { ingredientId: 'ing_tuna', name: 'Canned Tuna', amount: 1, unit: 'can' },
      { ingredientId: 'ing_eggs', name: 'Eggs', amount: 2, unit: 'pcs' },
      { ingredientId: 'ing_spinach', name: 'Fresh Spinach', amount: 100, unit: 'g' },
      { ingredientId: 'ing_tomato', name: 'Fresh Tomatoes', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_bell_pepper', name: 'Bell Pepper', amount: 0.5, unit: 'pcs' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 1, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Boil eggs in a small pot of water for 6-7 minutes for jammy yolks (or 9 minutes for hard-boiled). Plunge into cold water, peel, and halve.',
      'Drain the canned tuna and flake gently with a fork.',
      'Wash spinach and arrange as a lush green bed in a shallow serving bowl.',
      'Slice tomatoes and bell peppers into thin wedges.',
      'Arrange flaked tuna, sliced vegetables, and halved eggs neatly over the spinach bed.',
      'Drizzle extra virgin olive oil over the bowl, sprinkle with sea salt and cracked black pepper, and enjoy.',
    ],
  },
  {
    id: 'meal_mushroom_spinach_omelette',
    name: 'Golden Mushroom & Melted Cheese Omelette',
    shortDescription: 'Fluffy farm-style folded omelette stuffed with buttery sautéed mushrooms, spinach, and cheddar.',
    category: 'Quick & Easy',
    difficulty: 'Easy',
    baseServings: 1,
    prepTimeMinutes: 5,
    cookingTimeMinutes: 10,
    totalTimeMinutes: 15,
    caloriesPerServing: 310,
    protein: 21,
    carbohydrates: 5,
    fat: 22,
    fitnessSuitability: false,
    emoji: '🍳',
    chefTip: 'Keep heat medium-low so the eggs cook gently without browning excessively.',
    tags: ['Breakfast for Dinner', '15 Min', 'Vegetarian'],
    ingredients: [
      { ingredientId: 'ing_eggs', name: 'Eggs', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_mushroom', name: 'Cremini Mushrooms', amount: 80, unit: 'g' },
      { ingredientId: 'ing_spinach', name: 'Fresh Spinach', amount: 50, unit: 'g' },
      { ingredientId: 'ing_cheese', name: 'Cheddar Cheese', amount: 30, unit: 'g' },
      { ingredientId: 'ing_butter', name: 'Unsalted Butter', amount: 1, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Slice mushrooms thinly. In a small non-stick pan, melt 0.5 tbsp butter and sauté mushrooms for 3 minutes until softened and juices release.',
      'Toss in fresh spinach and stir for 30 seconds until just wilted. Transfer filling to a plate.',
      'Whisk eggs with a splash of water, salt, and black pepper until completely smooth and slightly frothy.',
      'Wipe pan clean, melt remaining butter over medium-low heat. Pour in beaten eggs and let set around the edges.',
      'Spoon sautéed mushroom-spinach filling and shredded cheese across one half of the omelette.',
      'Gently fold the other half over the filling, slide onto a warm plate, and serve.',
    ],
  },
  {
    id: 'meal_garlic_butter_shrimp_rice',
    name: 'Sizzling Garlic Butter Shrimp & Rice',
    shortDescription: 'Plump shrimp pan-seared in rich garlic butter and light soy glaze, served over fluffy steamed rice.',
    category: 'Regular',
    difficulty: 'Easy',
    baseServings: 2,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 15,
    totalTimeMinutes: 25,
    caloriesPerServing: 435,
    protein: 31,
    carbohydrates: 51,
    fat: 13,
    fitnessSuitability: true,
    emoji: '🍤',
    chefTip: 'Shrimp cooks quickly—remove from heat the moment they turn opaque pink and curl into a C-shape.',
    tags: ['Date Night', 'Seafood', 'Quick Gourmet'],
    ingredients: [
      { ingredientId: 'ing_shrimp', name: 'Fresh Shrimp', amount: 300, unit: 'g' },
      { ingredientId: 'ing_rice', name: 'Jasmine Rice', amount: 1.5, unit: 'cups' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 4, unit: 'cloves' },
      { ingredientId: 'ing_butter', name: 'Unsalted Butter', amount: 2, unit: 'tbsp' },
      { ingredientId: 'ing_bell_pepper', name: 'Bell Pepper', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_soy_sauce', name: 'Soy Sauce', amount: 1, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Cook jasmine rice in a pot or rice cooker until tender and fluffy.',
      'Peel and devein shrimp if necessary, patting completely dry with paper towel.',
      'Thinly slice garlic cloves and cut bell pepper into bite-sized strips.',
      'Melt butter in a large skillet over medium heat. Sauté sliced garlic for 1 minute until fragrant and lightly golden.',
      'Turn heat up to medium-high. Add shrimp and bell peppers in a single layer. Sear for 2 minutes per side until pink and cooked through.',
      'Drizzle with soy sauce and black pepper, toss gently for 30 seconds, and spoon immediately over warm bowls of jasmine rice.',
    ],
  },
  {
    id: 'meal_homestyle_chicken_soup',
    name: 'Cozy Homestyle Chicken & Veggie Soup',
    shortDescription: 'Simmered tender chicken breast with pasta ribbons, carrots, onions, and greens in savory broth.',
    category: 'Family Meal',
    difficulty: 'Medium',
    baseServings: 4,
    prepTimeMinutes: 15,
    cookingTimeMinutes: 45,
    totalTimeMinutes: 60,
    caloriesPerServing: 355,
    protein: 35,
    carbohydrates: 39,
    fat: 7,
    fitnessSuitability: true,
    emoji: '🍲',
    chefTip: 'Simmering on low heat gently poaches the chicken breast, keeping it wonderfully moist and tender.',
    tags: ['Nourishing', 'Soothing', 'Family Favorite'],
    ingredients: [
      { ingredientId: 'ing_chicken', name: 'Chicken Breast', amount: 450, unit: 'g' },
      { ingredientId: 'ing_pasta', name: 'Pasta (Spaghetti/Penne)', amount: 200, unit: 'g' },
      { ingredientId: 'ing_carrot', name: 'Carrots', amount: 2, unit: 'pcs' },
      { ingredientId: 'ing_onion', name: 'Yellow Onion', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_garlic', name: 'Garlic', amount: 3, unit: 'cloves' },
      { ingredientId: 'ing_spinach', name: 'Fresh Spinach', amount: 100, unit: 'g' },
      { ingredientId: 'ing_olive_oil', name: 'Olive Oil', amount: 1, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 2, unit: 'pinch' },
    ],
    instructions: [
      'Dice the onion, slice carrots into coins, and mince garlic cloves.',
      'In a large soup pot, warm olive oil over medium heat. Add onion, carrots, and garlic; sauté for 5 minutes until lightly softened.',
      'Pour in 6 cups of water (or broth if on hand), add whole chicken breasts, salt, and black pepper. Bring to a gentle boil, then lower heat, cover, and simmer for 20 minutes until chicken is cooked through.',
      'Remove chicken breast to a cutting board and shred with two forks.',
      'Add pasta to the simmering pot and cook for 8-10 minutes until tender.',
      'Return shredded chicken to the pot along with fresh spinach. Stir for 2 minutes until spinach wilts, taste for seasoning, and ladle into deep bowls.',
    ],
  },
  {
    id: 'meal_cheesy_potato_hash',
    name: 'Skillet Cheesy Potato & Egg Hash',
    shortDescription: 'Golden diced potatoes crisped in butter, topped with melted sharp cheddar and sunny fried eggs.',
    category: 'Regular',
    difficulty: 'Easy',
    baseServings: 3,
    prepTimeMinutes: 10,
    cookingTimeMinutes: 30,
    totalTimeMinutes: 40,
    caloriesPerServing: 415,
    protein: 17,
    carbohydrates: 46,
    fat: 19,
    fitnessSuitability: false,
    emoji: '🍳',
    chefTip: 'Create small wells in the crispy potato bed and crack the eggs directly into them for one-pan magic.',
    tags: ['Brunch', 'Comfort', 'Vegetarian'],
    ingredients: [
      { ingredientId: 'ing_potatoes', name: 'Russet Potatoes', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_eggs', name: 'Eggs', amount: 3, unit: 'pcs' },
      { ingredientId: 'ing_cheese', name: 'Cheddar Cheese', amount: 80, unit: 'g' },
      { ingredientId: 'ing_onion', name: 'Yellow Onion', amount: 1, unit: 'pcs' },
      { ingredientId: 'ing_butter', name: 'Unsalted Butter', amount: 2, unit: 'tbsp' },
      { ingredientId: 'ing_black_pepper', name: 'Black Pepper', amount: 1, unit: 'pinch' },
      { ingredientId: 'ing_salt', name: 'Table Salt', amount: 1, unit: 'pinch' },
    ],
    instructions: [
      'Dice potatoes into small 1cm cubes. Finely chop the yellow onion.',
      'In a large non-stick skillet, melt 1.5 tbsp butter over medium-high heat. Add diced potatoes and onion with salt.',
      'Cook without stirring for 4 minutes to develop a crisp crust, then stir and cook for another 10-12 minutes until potatoes are golden and tender.',
      'Sprinkle shredded cheddar cheese evenly over the top of the hot potatoes.',
      'Make 3 shallow wells with your spoon in the hash. Crack an egg into each well.',
      'Cover the pan with a lid and cook on low heat for 4-5 minutes until egg whites are set and yolks are runny. Season with black pepper and serve warm.',
    ],
  },
];
